In [5]:
from keras.models import load_model
import cv2
import numpy as np

In [6]:
model=load_model('face_detection_new.model')

In [7]:
face_clsfr=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
source=cv2.VideoCapture(0)
labels_dict={ 0:'with_mask', 1:'with_helmet',2:'without_mask'}
color_dict={0:(0,255,0),1:(0,0,255),2:(255,0,0)}

In [8]:
img_size=224
while True:
    ret, img = source.read()
    if not ret:
        break
    
    color = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    faces = face_clsfr.detectMultiScale(color, 1.3, 5)

    for x, y, w, h in faces:
        face_img = color[y:y + w, x:x + w]
        resize = cv2.resize(face_img, (img_size, img_size))
        reshaped = np.reshape(resize, (1, img_size, img_size, 3))
        result = model.predict(reshaped)
        label = np.argmax(result, axis=1)[0]

        cv2.rectangle(img, (x, y), (x + w, y + h), color_dict[label], 3)
        cv2.rectangle(img, (x, y - 40), (x + w, y), color_dict[label], -1)
        cv2.putText(img, labels_dict[label], (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 3)

    cv2.imshow('LIVE', img)
    key = cv2.waitKey(1)

    if key == 27:
        break

cv2.destroyAllWindows()
source.release()

1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 20ms/step


1/1 [==============================] - 0s 21ms/step


1/1 [==============================] - 0s 20ms/step


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 19ms/step


In [6]:
import os
import cv2
import numpy as np

img_size = 224

# Load your trained model. Make sure to replace 'model' with your actual model loading code.
# For example, if your model is saved as 'my_model.h5', you can load it like this:
# from keras.models import load_model
# model = load_model('my_model.h5')

test_path = '/home/dmns/Desktop/jupyternotebook/CNN/Face-mask-classification/data/train/with_helmet'

img_names = os.listdir(test_path)
category_dict ={ 0:'with_mask', 1:'with_helmet',2:'without_mask'}

for img_name in img_names:
    img = cv2.imread(os.path.join(test_path, img_name))
    if img is None:
        print(f"Failed to load image: {os.path.join(test_path, img_name)}")
        continue  # Skip this image and continue with the next one

    #h, w = img.shape[0:2]  # Height and width of the image

    resize = cv2.resize(img, (224, 224))
    reshaped = np.reshape(resize, (1, 224, 224, 3))
    result = model.predict(reshaped)
    label = np.argmax(result, axis=1)[0]
    acc = int(np.max(result) * 100)

    print(result, label, category_dict[label], acc)

    img[0:50, 0:w] = [0, 255, 0]
    cv2.putText(img, category_dict[label], (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 3)
    cv2.putText(img, str(acc) + '%', (120, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 3)

    cv2.imshow('LIVE', img)
    k = cv2.waitKey(1000)
    if k == 27:
        break

cv2.destroyAllWindows()



1/1 [==============================] - 0s 21ms/step
[[9.9562943e-01 2.7836757e-04 4.0923096e-03]] 0 with_mask 99
1/1 [==============================] - 0s 33ms/step
[[0.08192224 0.9124774  0.0056004 ]] 1 with_helmet 91
1/1 [==============================] - 0s 23ms/step
[[0.22821009 0.7414124  0.03037753]] 1 with_helmet 74
1/1 [==============================] - 0s 20ms/step
[[0.08316682 0.91109    0.00574316]] 1 with_helmet 91
1/1 [==============================] - 0s 20ms/step
[[0.9202063  0.04558181 0.03421191]] 0 with_mask 92
1/1 [==============================] - 0s 22ms/step
[[0.37345976 0.54148495 0.08505526]] 1 with_helmet 54
1/1 [==============================] - 0s 22ms/step
[[0.0928982  0.9034101  0.00369162]] 1 with_helmet 90
1/1 [==============================] - 0s 24ms/step
[[0.55490184 0.08328665 0.36181143]] 0 with_mask 55
1/1 [==============================] - 0s 20ms/step
[[9.9804282e-01 1.3578546e-04 1.8213448e-03]] 0 with_mask 99
1/1 [==============================]